version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: soc_postgres
    environment:
      POSTGRES_USER: socuser
      POSTGRES_PASSWORD: socpassword
      POSTGRES_DB: soc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: